### PR TITLE
Update to fix compatibility with emotion 10

### PR DESCRIPTION
**Pull request by SimeonC**
Emotion 10 also have renamed their packages. Creating two exports so there is still backwards compatibility if needed.

I figured as we have a major version in the works here we should keep the `emotion` export as 10 instead of doing `grid/emotion10` and `grid/emotion9` as the 9 export will eventually go away.

### CODE REVIEW

**Comment by SimeonC** [comment]
@jxnblk Can you help shed some light onto why Travis doesn't pass? First off it complained about package-lock being different now it has some obscure sha error?
Tests and build pass on my local machine.

**Comment by SimeonC** [comment]
@jxnblk Thanks for the tip, I tried that but it didn't change the package-lock file. I didn't remove the peerDependencies as it would have conflicted with https://github.com/rebassjs/grid/pull/158
I can just remove any changes to the peerDependencies then it won't conflict?

**Comment by jxnblk** [comment]
Oh, missed the other PR, sorry. I'll get that merged in first. But yeah, other than doing `git checkout package-lock.json` to reset it, I'm not sure what else to advise

**Comment by jxnblk** [comment]
I branched off of this one to try reseting the lock file and it seems to pass in travis now, see this branch for comparison https://github.com/rebassjs/grid/tree/SimeonC-emotion-fix-lock-file

**Comment by SimeonC** [comment]
Hmmm, I must be running a different version of `node/npm` - I don't know what version travis is using. What version of `node/npm` are you using?
If that's the case I'll add a [`.nvmrc`](https://github.com/creationix/nvm#nvmrc) file that should help alleviate those kinds of issues.

**Comment by jxnblk** [comment]
I'd like to have your contribution in here if possible, but also wanna make sure that contributing to this project works as expected. I don't think an `.nvmrc` file really should be necessary, but this project should work with Node 10 and npm 6

**Comment by SimeonC** [comment]
OK, I'm on Node 8 and npm 6 as well so there shouldn't be any problems.
This time I tried deleting node_modules and package-lock and that seems to have worked so I think I may have just installed it the first time pointing at my companies private npm instead of the public one or something.

**Pull request merged**
